define([], function () {


    var Events = {};

    /**
     * Given an event generated by clicking <a href='#something'> return a jquery element referencing the link and a string
     * with the value of the href attribute, minus the '#' character.
     */
    Events.eventDetail = function (event) {
        event.preventDefault();
        var link = $(event.target),
            target = link.attr('href'),
            actionName = target.replace('#', '');
        return { link: link, actionName: actionName};
    };

    return Events;

});